### ISSUE TITLE
Viewmodel for profile page

### ISSUE THREAD

**Issue by Mai-LinhC** [Assocify-Team/Assocify#115]
- [x] Change my profile #120 
- [x] Go to my settings #122 
- [x] Change my association #123 
- [x] Go to association settings #124 
- [x] See my role in the current asso #217

**Comment by Mai-LinhC** [comment]
Actual time (current) : 2 + 6
