### ISSUE TITLE
Add caching to APIs

### ISSUE THREAD

**Issue by SekoiaTree** [Assocify-Team/Assocify#206]
- [x] AssociationAPI (handled by #241)
- [x] BudgetAPI (handled by #303)
- [x] BalanceAPI (handled by #305)
- [x] AccountingCategoryAPI (handled by #307)
- [x] AccountSubCategoryAPI (handled by #307)
- [x] EventAPI (handled by #309)
- [x] ReceiptAPI (handled by #302)
- [x] TaskAPI (handled by #310)
- [x] UserAPI (handled by #308)
